# Generated by Django 4.2.26 on 2025-11-21 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_rename_postpage_postcontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostContent',
            new_name='PostContents',
        ),
    ]
