# Generated by Django 4.2.26 on 2025-11-21 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_rename_postcontent_postcontents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostContents',
            new_name='UserPost',
        ),
    ]
