# Generated by Django 4.2.26 on 2025-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_postcontents_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
